### ISSUE TITLE
Using Hugo static site builder

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/savandbros#20]
Mainly because it makes a static output which we can just upload to the server.
Another main reason having the ability to do i18n which is very important for us.

Right now the website is only one landing page and I'm ok with keeping it the way it is.
Let's have the design and content finalized and then move it to hugo.

It has some good https://gohugo.io/tools/starter-kits/ as well.

Resource: https://gohugo.io/content-management/multilingual/

**Comment by AmirSavand** [comment]
What about webpack? We can just build it with webpack and translation?

Which one's more efficient and faster?

**Comment by Alir3z4** [comment]
Webpack cannot give us translations etc.
Webpack only is a build tool.
The translations will happen via Angular or React or what so ever framework
we chose to go with and by the nature of all the translation libraries all
the localized strings will be loaded in async which is a no no, otherwise
the whole thing should be Server Side Rendered which again is another
problem for another century.

What Hugo does, is simply read the content files md/html/etc and generates
static files, no async or server required.
Means for every language we define, a separate html will be generated.

Makes sense ?

**Comment by AmirSavand** [comment]
Yea thought so.

**Comment by AmirSavand** [comment]
When should we do this? After we done with the landing?

**Comment by Alir3z4** [comment]
Yes, once the design has been finalized.
You can start moving it there.

**Comment by Alir3z4** [comment]
Once you have https://github.com/SavandBros/savandbros/pull/19, please start working on this.

**Comment by Alir3z4** [comment]
To start a home page https://gohugo.io/templates/homepage/

**Comment by Alir3z4** [comment]
You may use this https://github.com/netlify/victor-hugo which has tons of features and even forms, shortcuts, etc.

We can also make an auto deploy to netlify hosting without needing to have the stuff on kloud51 servers.
Otherwise, I guess we can use the that starter template and `rsync` the build dir to k51 servers.

What do you think ?

**Comment by AmirSavand** [comment]
Since this project is not an active project and once it's done we'll leave it, I guess the normal FTP upload is ok for now.

**Comment by Alir3z4** [comment]
I wanted to use those starters because it would make compression, modifications etc
