### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/savandbros#28]
When I run `hego` it creates the 3 language folders but it should redirect the `/` to `/en/`.

When I run `hugo server -D` the `/` is english.

How can I use gulp? The command is registered.

**Comment by AmirSavand** [comment]
Got the gulp working by installing it globally but hugo still doesn't handle `/` 404.

**Comment by AmirSavand** [comment]
Can we make an `index.html` that redirects to `/en` or something? I think this should be handled by hugo not gulp.

**Comment by Alir3z4** [comment]
This is fixed in https://github.com/SavandBros/savandbros/pull/30/commits/33753eb408758b5dd39a303fd66b5e386d823724

**Comment by AmirSavand** [comment]
Yes awesome.
