### ISSUE TITLE
Service sections

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/savandbros#9]
* IT
  * Cloud Computing 
  * Web Design & Hosting
  * Email Hosting
  * Managed Online store 
* Tourist and Travel to Russia 
  * Visit Visa
  * Hotel reservation
  * Flight ticket booking
  * Transfer
  * Moscow & St. Petersburg Tours
* Import/Export
  * Food
  * Carpet 
  * Electric & Appliances 

Basically these 3 are our main service categories and their sub categories.

**Comment by AmirSavand** [comment]
IT
 Cloud Computing
 Web Design & Hosting
 Email Hosting
 Managed Online Store

Tourist & Traveling
 Visit Visa
 Hotel reservation
 Flight ticket booking
 Transfer
 Tours

Import & Export
 Food
 Carpet
 Electric & Appliances

===

@Alir3z4 are these changes fine?
